all: compile run

compile:
	@javac homework1/*.java
run:
	@java homework1.TestClass1
	@echo "Press enter to insert TestClass2"
	@read REPLY
	@java homework1.TestClass2
	@echo "Press enter to insert TestClass3"
	@read REPLY	
	@java homework1.TestClass3
