all : javadoc compile run1_1 run1_2 run1_3 run1_4 run2_1 run2_2 run2_3 run2_4 run3_1 run3_2 run3_3 run3_4

javadoc:
	javadoc -d JavadocFirst homework3_first/*.java
	javadoc -d JavadocSecond homework3_second/*.java
	javadoc -d JavadocThird homework3_third/*.java

compile:
	javac homework3_first/*.java
	javac homework3_second/*.java
	javac homework3_third/*.java

run1_1:
	java homework3_first.TestClass1
run1_2:
	java homework3_first.TestClass2
run1_3:
	java homework3_first.TestClass3
run1_4:
	java homework3_first.TestClass4
run2_1:
	java homework3_second.TestClass1
run2_2:
	java homework3_second.TestClass2
run2_3:
	java homework3_second.TestClass3
run2_4:
	java homework3_second.TestClass4
run3_1:
	java homework3_third.TestClass1
run3_2:
	java homework3_third.TestClass2
run3_3:
	java homework3_third.TestClass3		
run3_4:
	java homework3_third.TestClass4				

